"""Add models and fields for client census import

Revision ID: 0662a1fee843
Revises: 9281d27761d7
Create Date: 2023-03-31 16:00:01.881861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0662a1fee843'
down_revision = '9281d27761d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_center',
    sa.Column('ext_ref', sa.String(), server_default='', nullable=True),
    sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_cost_center_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_center')),
    sa.UniqueConstraint('name', 'client_id', name=op.f('uq_cost_center_name'))
    )
    op.create_table('client_user_department',
    sa.Column('ext_ref', sa.String(), server_default='', nullable=True),
    sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_user_id'], ['client_user.id'], name=op.f('fk_client_user_department_client_user_id_client_user')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_client_user_department_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_user_department')),
    sa.UniqueConstraint('client_user_id', 'department_id', name=op.f('uq_client_user_department_client_user_id'))
    )
    op.create_table('department_location',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_department_location_department_id_department')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_department_location_location_id_location')),
    sa.PrimaryKeyConstraint('department_id', 'location_id', name=op.f('pk_department_location'))
    )
    op.create_table('department_position',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_department_position_department_id_department')),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], name=op.f('fk_department_position_position_id_position')),
    sa.PrimaryKeyConstraint('department_id', 'position_id', name=op.f('pk_department_position'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_rate', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('bill_rate', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('cost_center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_assignment_cost_center_id_cost_center'), 'cost_center', ['cost_center_id'], ['id'])

    with op.batch_alter_table('client_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reports_to_client_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_client_user_cost_center_id_cost_center'), 'cost_center', ['cost_center_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_client_user_reports_to_client_user_id_client_user'), 'client_user', ['reports_to_client_user_id'], ['id'])

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owner_client_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accounting_approver_client_user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_department_number'), ['number', 'client_id'])
        batch_op.create_foreign_key(batch_op.f('fk_department_accounting_approver_client_user_id_client_user'), 'client_user', ['accounting_approver_client_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_department_owner_client_user_id_client_user'), 'client_user', ['owner_client_user_id'], ['id'])

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pay_rate_min', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('pay_rate_max', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('is_remote', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('fk_position_department_id_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_position_department_id_department', 'department', ['department_id'], ['id'])
        batch_op.drop_column('is_remote')
        batch_op.drop_column('pay_rate_max')
        batch_op.drop_column('pay_rate_min')
        batch_op.drop_column('requirements')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_department_owner_client_user_id_client_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_department_accounting_approver_client_user_id_client_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_department_number'), type_='unique')
        batch_op.drop_column('accounting_approver_client_user_id')
        batch_op.drop_column('owner_client_user_id')
        batch_op.drop_column('number')

    with op.batch_alter_table('client_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_client_user_reports_to_client_user_id_client_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_client_user_cost_center_id_cost_center'), type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('reports_to_client_user_id')
        batch_op.drop_column('cost_center_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignment_cost_center_id_cost_center'), type_='foreignkey')
        batch_op.drop_column('cost_center_id')
        batch_op.drop_column('bill_rate')
        batch_op.drop_column('pay_rate')

    op.drop_table('department_position')
    op.drop_table('department_location')
    op.drop_table('client_user_department')
    op.drop_table('cost_center')
    # ### end Alembic commands ###
