"""Add minimal approval fields on Requisition

Revision ID: 71ead369c78c
Revises: 737d7b5b1551
Create Date: 2023-05-16 16:21:04.063439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ead369c78c'
down_revision = '737d7b5b1551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition', schema=None) as batch_op:
        approvalstate_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstate')
        approvalstate_enum.create(op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('approval_state', approvalstate_enum, server_default='PENDING', nullable=True))
        batch_op.add_column(sa.Column('approvals', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition', schema=None) as batch_op:
        batch_op.drop_column('approvals')
        batch_op.drop_column('approval_state')

    # ### end Alembic commands ###
