"""Add ImportLog table and import_id to base model for sync-client/sync-undo commands

Revision ID: 737d7b5b1551
Revises: 1c62c1aa899d
Create Date: 2023-05-09 16:13:15.569789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737d7b5b1551'
down_revision = '1c62c1aa899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_log',
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('ext_ref', sa.String(), server_default='', nullable=True),
    sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE_SHEET', name='importsource'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_log'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('auth_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('category_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('client_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('client_user_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('contract_term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('contract_term_definition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('job_classification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('pay_scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('requisition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('requisition_present_worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('requisition_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('worker_environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_environment', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('requisition_type', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('requisition_present_worker', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('requisition', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('pay_scheme', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('job_classification', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('contract_term_definition', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('contract_term', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('client_user_department', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('client_user', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('category_item', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('auth_provider', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('import_id')

    op.drop_table('import_log')
    # ### end Alembic commands ###
