"""Add default audit metadata fields to DeclarativeBase model

Revision ID: 7803c1899519
Revises: 7ef7a7c09672
Create Date: 2023-01-23 16:02:56.591493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7803c1899519'
down_revision = '7ef7a7c09672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext_ref', sa.String(), server_default='', nullable=True))
        batch_op.add_column(sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('modified_date')
        batch_op.drop_column('modified_uid')
        batch_op.drop_column('created_date')
        batch_op.drop_column('created_uid')
        batch_op.drop_column('ext_ref')

    # ### end Alembic commands ###
