"""Fix User-Client-Role relationship

Revision ID: b4fe551c7efd
Revises: f76cf38caf25
Create Date: 2023-02-27 21:32:06.411508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fe551c7efd'
down_revision = 'f76cf38caf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user',
    sa.Column('ext_ref', sa.String(), server_default='', nullable=True),
    sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_client_user_client_id_client')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_client_user_role_id_role')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_client_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_user')),
    sa.UniqueConstraint('client_id', 'user_id', name=op.f('uq_client_user_client_id'))
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_permission_entity'), ['entity', 'field', 'action'])

    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_id_role', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_user_role_id_role', 'role', ['role_id'], ['id'])

    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_permission_entity'), type_='unique')

    op.drop_table('client_user')
    # ### end Alembic commands ###
