"""Add dummy Requisition model.

Revision ID: f76cf38caf25
Revises: 879065c732b5
Create Date: 2023-02-22 20:47:57.508253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76cf38caf25'
down_revision = '879065c732b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisition',
    sa.Column('ext_ref', sa.String(), server_default='', nullable=True),
    sa.Column('created_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_uid', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisition'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisition')
    # ### end Alembic commands ###
